#!/usr/bin/env bash
# nginx web server install commands
sudo apt-get -y update
sudo apt-get  -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod u+x /var/www/html/index.nginx-debian.html 
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
