#!/usr/bin/env bash
# nginx web server install commands
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod u+x /var/www/html/index.nginx-debian.html 
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
