#!/usr/bin/env bash
# Nginx configuration file.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod u+x /var/www/html/index.nginx-debian.html
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=Fy1QRXplvDE permanent; }' /etc/nginx/sites-available/default
sudo service nginx start

