#!/usr/bin/env bash
# second server config.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
conf="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "s/server_name _;/$conf/" /etc/nginx/sites-available/default
sudo service nginx stop
sudo service nginx start
