#!/usr/bin/env bash
# Install/configure HAproxy(load balancer)
sudo apt-get -y install haproxy
cfg=\
"
frontend http_web
        bind *:80
        stats uri /haproxy?stats
        default_backend backend
backend backend
        balance roundrobin
        server 4290-web-01 54.91.126.79:80 check
        server 4290-web-02 18.208.141.223:80 check
"
 echo "$cfg" | sudo tee /etc/haproxy/haproxy.cfg
 echo "ENABLED=1" | sudo tee /etc/default/haproxy
 sudo service haproxy stop
 sudo service haproxy start
 