#!/usr/bin/env bash
# displays "to infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.
#+ displays "i am invincible!!!"when receiving a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'eccho "I am invincible"' SIGTERM
done
